### ISSUE TITLE
Assigner aborts when comparing sha2<256>::block_types

### ISSUE THREAD

**Issue by color-typea** [NilFoundation/zkllvm#134]
**Problem:** If circuit contains comparing sha2<256>::block_types for equality, assigner aborts with 

```
UNREACHABLE at zkllvm/libs/assigner/include/nil/blueprint/parser.hpp:460
        Unsupported icmp operand type
```

**Steps to reproduce:**

1. Put the following files into zkllvm/examples

sha2_256_verify.cpp
```
#include <nil/crypto3/hash/algorithm/hash.hpp>
#include <nil/crypto3/hash/sha2.hpp>

using namespace nil::crypto3;

bool is_same(
    typename hashes::sha2<256>::block_type block0,
    typename hashes::sha2<256>::block_type block1) {

    return block0[0] == block1[0] && block0[1] == block1[1];
}

[[circuit]] bool sha256_verify_example(
    typename hashes::sha2<256>::block_type first_input_block,
    typename hashes::sha2<256>::block_type second_input_block,
    typename hashes::sha2<256>::block_type expected_result
) {

    typename hashes::sha2<256>::block_type hash_result = hash<hashes::sha2<256>>(first_input_block, second_input_block);

    auto result = is_same(hash_result, expected_result);
    return result;
}
```

sha2_256_verify.inp
```
[ {"vector": [1,2]},
  {"vector": [3,4]},
  {"vector": ["304141736655649042377702932067206617823", "218022910167622286964932101416791437254"]} ]
```

**Note:** `is_same` is taken from https://docs.nil.foundation/zkllvm/tutorial/01-hashes

2. Add the circuit definition into zkllvm/examples/CMakeLists.txt

```
add_example(sha256_verify_example SOURCES sha2_256_verify.cpp INPUT sha2_256_verify.inp)
```

3. Compile the circuit: `make -C ${ZKLLVM_BUILD:-build} sha256_verify_example -j$(nproc)`
3.1. Ensure that `sha2_256_verify.cpp.ll` or `sha2_256_verify.cpp.bc` appears in build/examples. 
3.2. Also, intermittently it is called sha256_verify_example.ll
4. Run assigner: ` ./build/bin/assigner/assigner -b ./build/examples/sha2_256_verify.cpp.ll -i examples/sha2_256_verify.inp -t assignment.tbl -c circuit.crct -e pallas`

**Expected output:** Assigner completes successfully, circuit.crct and assignment.tbl are created
**Actual outcome:** 

```
UNREACHABLE at ~/zkllvm/libs/assigner/include/nil/blueprint/parser.hpp:460
        Unsupported icmp operand type
Aborted (core dumped)
```

**Toolchain versions:**
* Compiler: clang version 16.0.0 (git@github.com:NilFoundation/zkllvm-circifier.git 158b3390eb47c037f43d07e82b5a9b0cc8397489)
* Assigner: built on [ze94b1cbdbbb6f89fc0e07b9dd0511236b1612455](https://github.com/NilFoundation/zkllvm/commit/e94b1cbdbbb6f89fc0e07b9dd0511236b1612455)

**Comment by makxenov** [comment]
No longer can be reproduced
