### ISSUE TITLE
Vector inputs are not supported?

### ISSUE THREAD

**Issue by color-typea** [NilFoundation/zkllvm#136]
**Problem:** Circuit with vector input type is failing assignment.

**Circuit:**

```
[[circuit]] bool merkelize_uint64_list(std::vector<uint64_t> values) {
    return true;
}
```

**Input:**
```
[ 
    {"vector": [1, 2]}
]
```

**Steps to reproduce:**
Assuming circuit and input files are name circuit.cpp and circuit.inp + adding them to examples/CMakeLists.txt:

1. Compile the circuit: `cmake -C ${ZKLLVM_BUILD:-build} circuit_example -j$(nproc)`
2. Assign the circuit: `./build/bin/assigner/assigner -b ./build/examples/circuit_example.cpp.ll -i examples/merkleize_uint64_list.inp -t assignment.tbl -c circuit.crct -e pallas`

**Expected outcome:** Assignment succeeds, crct and tbl files are created
**Actual outcome:** Assigner fails with:

```
Got pointer argument, only pointers to std::array or char are supported
Public input must match the size of arguments
```

Questions:
* Are std::vector supported as circuit argument?
* If not, how can "dynamic" data can be used in circuits? "Dynamic data" here means data which length is not known during circuit development time, but is known at "runtime" (i.e. when proof will be requested)

**Toolchain versions:**
* Compiler: clang version 16.0.0 (git@github.com:NilFoundation/zkllvm-circifier.git 158b3390eb47c037f43d07e82b5a9b0cc8397489)
* Assigner: built on [ze94b1cbdbbb6f89fc0e07b9dd0511236b1612455](https://github.com/NilFoundation/zkllvm/commit/e94b1cbdbbb6f89fc0e07b9dd0511236b1612455)

**Comment by nkaskov** [comment]
Vectors input type is supposed to be used as a c-style container (int* int64_t).
Another option is to use std::array<int64_t, ...>. In case if you know the size of the input, this is a better option, since in circuits any dynamic-allocated memory is always more expensive (since the size of the table is unknown before the input).

**Comment by nkaskov** [comment]
Development of std::vector will be managed in another issue: https://github.com/NilFoundation/zkllvm/issues/138.
