### ISSUE TITLE
Transpiler segfaults on empty proof

### ISSUE THREAD

**Issue by color-typea** [NilFoundation/zkLLVM#153]
**Problem:** Transpiler fails with a segfault.

Circuit, input, assignment table and crct + valgrind analysis of segfault: https://gist.github.com/color-typea/abcf43f7555dfef760f89673ecd2805c

**Commands:**

```
mkdir output
./build/bin/assigner/assigner -b ./build/examples/circuit.ll -i ./examples/inputs/circuit.inp -c output/circuit.crct -t output/circuit.tbl -e pallas --check
 ./build/bin/transpiler/transpiler -i examples/inputs/circuit.inp -t output/circuit.tbl -c output/circuit.crct  -m gen-test-proof -o output
```

**Expected result:** Transpiler generates gate_argument.sol and gates in `output` folder + circuit_params.json and public_input.json
**Actual result:** Only circuit_params.json and public_input.json are generated, transpiler crashes with segfault

Toolchain versions:
* ZKLLVM: clang version 16.0.0 (git@github.com:NilFoundation/zkllvm-circifier.git 65a087de455b481e6d0c3b5b2e3e152097ea9bb6)
* Assigner: built on 65a087de455b481e6d0c3b5b2e3e152097ea9bb6
* Transpiler: built on 65a087de455b481e6d0c3b5b2e3e152097ea9bb6

**Comment by nkaskov** [comment]
Fixed, closed.
