### ISSUE TITLE
Balance_tree example is subtly broken

### ISSUE THREAD

**Issue by color-typea** [NilFoundation/zkllvm#184]
**Problem:** referencing any `precomputed_zero_hashes` except `precomputed_zero_hashes[potentially_non_zero_leaves_amount_log2]` (which is `precomputed_zero_hashes[4]`) causes assigner to abort.

**Steps to reproduce:**
1. Add `ypename hashes::sha2<256>::block_type zerohash = precomputed_zero_hashes[0];` anywhere in the `balance_tree` code

**Expected outcome:** Nothing changes, compilation and assignment works correctly
**Actual outcome:** Compilation succeeds, assignment fails with 

```
Assertion failed at /home/john/Projects/crypto/zkllvm/zkllvm/libs/assigner/include/nil/blueprint/parser.hpp:156:
        llvm::isa<llvm::ConstantField>(val) || llvm::isa<llvm::ConstantInt>(val)
Aborted (core dumped)
```

**Additional info:** I suspect balances_tree example works without the change because compiler inlines `precomputed_zero_hashes[potentially_non_zero_leaves_amount_log2]` and optimizes away `precomputed_zero_hashes` completely. LL bytecode for "working" example does not contain any references to precomputed_zero_hashes - see [gist](https://gist.github.com/color-typea/e11cf245028b5cf6664b1c9263ca54f7)

**Toolchain versions:**
**Toolchain versions:**
All built from source
zkkllvm - v0.0.86, d66350b67f0ddd4f15667db73b7f85428c01945e
zkllvm/libs/circifier - v0.0.33, c67458ea4d9f80a9bf61a37ccbef9b60ed11575a
zkllvm/libs/assigner - v0.0.39, d66350b67f0ddd4f15667db73b7f85428c01945e
zkllvm libs/transpiler - v0.0.9. b5fb9115404fa6a581dddd88c4068b2844ea43ad
```
./build/libs/circifier/llvm/bin/clang-16 --version
clang version 16.0.0 (git@github.com:NilFoundation/zkllvm-circifier.git c67458ea4d9f80a9bf61a37ccbef9b60ed11575a)
```

**Comment by color-typea** [comment]
@nkaskov , @NickVolynkin FYI

**Comment by nkaskov** [comment]
Hmm, interesting. We will check it. Thanks for noticing.
