### ISSUE TITLE
Outdated/False commands inside readme.md

### ISSUE THREAD

**Issue by cemdenizsel** [NilFoundation/zkLLVM#324]
Hi, 

here, 
`make -C ${ZKLLVM_BUILD:-build} circuit_cpp_examples -j$(sysctl -n hw.logicalcpu)`

`${ZKLLVM_BUILD:-build}/bin/assigner/assigner -b ${ZKLLVM_BUILD:-build}/examples/cpp/arithmetics_example.bc -i examples/inputs/arithmetics.inp -t assignment.tbl -c circuit.crct -e pallas`

second command does not run, because the path of the `${ZKLLVM_BUILD:-build}/examples/cpp/arithmetics_example.bc` file is wrong. Also the file type decleration `.bc` is wrong. so it should be `arithmetics_cpp_example_no_stdlib_arithmetics.cpp.ll`.

in total the command which i found working was this: 
`${ZKLLVM_BUILD:-build}/bin/assigner/assigner -b ${ZKLLVM_BUILD:-build}/examples/cpp/arithmetics_cpp_example_no_stdlib_arithmetics.cpp.ll -i examples/inputs/arithmetics.inp -t assignment.tbl -c circuit.crct -e pallas`

Thank you.

**Comment by nkaskov** [comment]
The names of the output ll files have changed, we need to update this part.
