### ISSUE TITLE
Build fails with static linking on MacOS x86-64

### ISSUE THREAD

**Issue by aleasims** [NilFoundation/zkLLVM#353]
When building zkLLVM on MacOS x86-64 with static linking enabled (`-DBUILD_SHARED_LIBS=FALSE`), linking error occurs:

```
[100%] Linking CXX executable assigner
duplicate symbol 'nil::crypto3::multiprecision::backends::window_bits(unsigned long)' in:
    CMakeFiles/assigner.dir/src/main.cpp.o
    ../../libs/circifier/llvm/lib/libLLVMZK.a(FieldArithmetics.cpp.o)
duplicate symbol 'nil::marshalling::operator|(nil::marshalling::status_type const&, nil::marshalling::status_type const&)' in:
    CMakeFiles/assigner.dir/src/main.cpp.o
    ../../libs/circifier/llvm/lib/libLLVMZK.a(FieldArithmetics.cpp.o)
ld: 2 duplicate symbols for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

Full build log may be found in `build-macos` action run:

https://github.com/NilFoundation/zkLLVM/actions/runs/6813384932/job/18527840836

**Comment by aleasims** [comment]
This is issue will be fixed with:

- [ ] NilFoundation/crypto3/issues/96

**Comment by x-mass** [comment]
As for https://github.com/NilFoundation/zkLLVM/commit/0b2834adab34d5d548379840e48ffe2b9283729d with https://github.com/NilFoundation/crypto3/commit/f4721b8ac397416732a0fe4bd66e26894008f2c6, assigner compiles just fine with `-DBUILD_SHARED_LIBS=FALSE`
<details><summary>Expand to see full list of SHAs</summary>
<pre><code>Main Repo SHA: 7cfec3b5cab8ac38271615894e4ae752191bd4e5
Entering 'cmake/modules'
18635efd511a22c00fa96d067eeecb5dc6c4c7b2
Entering 'libs/assigner'
16c1e6addb072fc5fed27d039e45b065d45cde59
Entering 'libs/assigner/cmake/modules'
29b5fb09f8fc5cdcf249186df9dc48d1ea6a36b7
Entering 'libs/blueprint'
c01092cee06378ef01b504bd6a57fa672c1249dc
Entering 'libs/blueprint/cmake/modules'
5e6b354eaa69f6a275992e08220e925c34ba0a19
Entering 'libs/circifier'
33feeabbd94451ee078d37bcaf0210ef2640933e
Entering 'libs/crypto3'
f4721b8ac397416732a0fe4bd66e26894008f2c6
Entering 'libs/crypto3/cmake/modules'
69d95b4d96d6fe7b6f4e47bcfdbc232ca1bd558d
Entering 'libs/crypto3/libs/algebra'
ed5d8b4b5941881c5b1d633e9e61ce3ee6cb722e
Entering 'libs/crypto3/libs/algebra/cmake/modules'
5e6b354eaa69f6a275992e08220e925c34ba0a19
Entering 'libs/crypto3/libs/block'
47540c71d0cd4bc81d90acbd95126cb117ef9d68
Entering 'libs/crypto3/libs/block/cmake/modules'
5e6b354eaa69f6a275992e08220e925c34ba0a19
Entering 'libs/crypto3/libs/codec'
f16e5eecc93b62a1382e5cc5502dee10b583d7cb
Entering 'libs/crypto3/libs/codec/cmake/modules'
5e6b354eaa69f6a275992e08220e925c34ba0a19
Entering 'libs/crypto3/libs/containers'
76f805a3ff92af9a6a07aabe024a465cc52e1bda
Entering 'libs/crypto3/libs/containers/cmake/modules'
5e6b354eaa69f6a275992e08220e925c34ba0a19
Entering 'libs/crypto3/libs/hash'
6b19019b64c9a3a6c242e5c1f39cdf8b9ece5b29
Entering 'libs/crypto3/libs/hash/cmake/modules'
5e6b354eaa69f6a275992e08220e925c34ba0a19
Entering 'libs/crypto3/libs/kdf'
9f18ed572f4848774cd4b05a411a701af03081d9
Entering 'libs/crypto3/libs/kdf/cmake/modules'
29b5fb09f8fc5cdcf249186df9dc48d1ea6a36b7
Entering 'libs/crypto3/libs/mac'
bbe8aba4a455572064879197a3099f8b03ef8583
Entering 'libs/crypto3/libs/mac/cmake/modules'
5e6b354eaa69f6a275992e08220e925c34ba0a19
Entering 'libs/crypto3/libs/marshalling/algebra'
f20a163457da731841f6c3e01e24679dd43b25f6
Entering 'libs/crypto3/libs/marshalling/algebra/cmake/modules'
5e6b354eaa69f6a275992e08220e925c34ba0a19
Entering 'libs/crypto3/libs/marshalling/core'
6b1940baad808b447796950c414e003061418b94
Entering 'libs/crypto3/libs/marshalling/core/cmake/modules'
5e6b354eaa69f6a275992e08220e925c34ba0a19
Entering 'libs/crypto3/libs/marshalling/multiprecision'
8d9a839ce1a423c3e78c01909f5cc71e9b5d2b5b
Entering 'libs/crypto3/libs/marshalling/multiprecision/cmake/modules'
5e6b354eaa69f6a275992e08220e925c34ba0a19
Entering 'libs/crypto3/libs/marshalling/zk'
3a8efcf62eba21e8b842518717ecfb9f0c2b1e81
Entering 'libs/crypto3/libs/marshalling/zk/cmake/modules'
5e6b354eaa69f6a275992e08220e925c34ba0a19
Entering 'libs/crypto3/libs/math'
b6e1a8ee9a70882fb793896c162ecc34df79d779
Entering 'libs/crypto3/libs/math/cmake/modules'
5e6b354eaa69f6a275992e08220e925c34ba0a19
Entering 'libs/crypto3/libs/modes'
c8d6f4bbbb7a9ac9dab7b3fdedcc0420bfc6e7ba
Entering 'libs/crypto3/libs/modes/cmake/modules'
5e6b354eaa69f6a275992e08220e925c34ba0a19
Entering 'libs/crypto3/libs/multiprecision'
da5ee0ae399ada85cf568e09b9bd7da1cf034643
Entering 'libs/crypto3/libs/multiprecision/cmake/modules'
5e6b354eaa69f6a275992e08220e925c34ba0a19
Entering 'libs/crypto3/libs/passhash'
4a5d7507642ba5d36dc7ee7746fd066a6ac108b2
Entering 'libs/crypto3/libs/passhash/cmake/modules'
29b5fb09f8fc5cdcf249186df9dc48d1ea6a36b7
Entering 'libs/crypto3/libs/pbkdf'
c177b3bd0e2ea75b9d33da93cf2aa4dea283de9b
Entering 'libs/crypto3/libs/pbkdf/cmake/modules'
29b5fb09f8fc5cdcf249186df9dc48d1ea6a36b7
Entering 'libs/crypto3/libs/pkpad'
ca1546144dec3ff35970434ff3a61bddea6dbe9c
Entering 'libs/crypto3/libs/pkpad/cmake/modules'
5e6b354eaa69f6a275992e08220e925c34ba0a19
Entering 'libs/crypto3/libs/pubkey'
735a7485a89d96c6e7c7193f468a33f385bb3eec
Entering 'libs/crypto3/libs/pubkey/cmake/modules'
5e6b354eaa69f6a275992e08220e925c34ba0a19
Entering 'libs/crypto3/libs/random'
c041366e7be4d27e023363acbe54c76a40afcb29
Entering 'libs/crypto3/libs/random/cmake/modules'
5e6b354eaa69f6a275992e08220e925c34ba0a19
Entering 'libs/crypto3/libs/stream'
10745e01fe8c8fc7997561185254e7d8bcce8d00
Entering 'libs/crypto3/libs/stream/cmake/modules'
5e6b354eaa69f6a275992e08220e925c34ba0a19
Entering 'libs/crypto3/libs/threshold'
93286cd47dc6d01e468377ed0a00e19f75a8ea86
Entering 'libs/crypto3/libs/threshold/cmake/modules'
29b5fb09f8fc5cdcf249186df9dc48d1ea6a36b7
Entering 'libs/crypto3/libs/vdf'
867319d7efb884992efead10cd296867d231c1d2
Entering 'libs/crypto3/libs/vdf/cmake/modules'
29b5fb09f8fc5cdcf249186df9dc48d1ea6a36b7
Entering 'libs/crypto3/libs/zk'
6e53d34b6a1f6e9c6d399378b1d4bd1e98a0e0d9
Entering 'libs/crypto3/libs/zk/cmake/modules'
5e6b354eaa69f6a275992e08220e925c34ba0a19
Entering 'libs/rslang'
a516bc53931245040a6e42e9c2c02793c8eb86bd
Entering 'libs/rslang/library/backtrace'
e1c49fbd6124a1b626cdf19871aff68c362bdf07
Entering 'libs/rslang/library/stdarch'
d77878b7299dd7e286799a6e8447048b65d2a861
Entering 'libs/rslang/src/doc/book'
72187f5cd0beaaa9c6f584156bcd88f921871e83
Entering 'libs/rslang/src/doc/edition-guide'
2751bdcef125468ea2ee006c11992cd1405aebe5
Entering 'libs/rslang/src/doc/embedded-book'
99ad2847b865e96d8ae7b333d3ee96963557e621
Entering 'libs/rslang/src/doc/nomicon'
388750b081c0893c275044d37203f97709e058ba
Entering 'libs/rslang/src/doc/reference'
d43038932adeb16ada80e206d4c073d851298101
Entering 'libs/rslang/src/doc/rust-by-example'
07e0df2f006e59d171c6bf3cafa9d61dbeb520d8
Entering 'libs/rslang/src/doc/rustc-dev-guide'
b123ab4754127d822ffb38349ce0fbf561f1b2fd
Entering 'libs/rslang/src/llvm-project'
d404cba4e39df595710869988ded7cbe1104b52f
Entering 'libs/rslang/src/tools/cargo'
589f0ee65866f9c913df1404dff7f71374a2f01b
Entering 'libs/stdlib'
98b0c4e9cd2854e96856ea88d56971c8c80737eb
Entering 'libs/transpiler'
ee8145bf0441c6e27db64a66045e3da2d82717ca
Entering 'libs/transpiler/cmake/modules'
e7dfac709106a840ebf293190497793b069bfe57</code></pre>
</details>

**Comment by aleasims** [comment]
Closing as fixed
