### ISSUE TITLE
Deb package 0.1.9 falls with errors in std

### ISSUE THREAD

**Issue by nkaskov** [NilFoundation/zkLLVM#381]
Probably, after the updates in libc, deb package installation falls.
![image](https://github.com/NilFoundation/zkLLVM/assets/20524659/526657df-f166-42ae-a0bb-e8f101ec0dfb)

**Comment by nkaskov** [comment]
Priority is High but not Urgent. I have a workaround.

**Comment by akokoshn** [comment]
Issue caused by commit:
[Install zkllvm-libc.ll and related headers by default](https://github.com/NilFoundation/zkllvm-stdlib/commit/d26ebc66f0bb9990b596ec31ec02941ab9c93967)

**Comment by akokoshn** [comment]
Revert commit in stdlib: https://github.com/NilFoundation/zkllvm-stdlib/pull/9
Update submodule: https://github.com/NilFoundation/zkLLVM/pull/385

**Comment by akokoshn** [comment]
merged fix into zkLLVM master/ stdlib master
