### ISSUE TITLE
Add CI builds on macOS

### ISSUE THREAD

**Issue by NickVolynkin** [NilFoundation/zkllvm#39]
Follow-up to #2: build zkllvm in CI on macOS, at least in one environment (os version × compiler × boost).

**Comment by ameya-deshmukh** [comment]
@NickVolynkin I'd like to take this up, can you assign me?

**Comment by NickVolynkin** [comment]
@ameya-deshmukh Hi! It's already in progress, see https://github.com/NilFoundation/zkllvm/pull/38. But you're welcome to review the code if you like.

**Comment by ameya-deshmukh** [comment]
Thank you! Didn't see that
What's another issue I can work on/you need help with? Maybe I can work on that

**Comment by NickVolynkin** [comment]
@ameya-deshmukh let me think a little :)
To be honest, we're not quite ready for external contributors, because there are no contribution guidelines and very little CI. But anyway, I'm glad that you offer your help.

**Comment by ameya-deshmukh** [comment]
Oh, no worries :)
