### ISSUE TITLE
Skip excessive tables and constraints generation for multi-prover

### ISSUE THREAD

**Issue by nkaskov** [NilFoundation/zkLLVM#406]
For the aggregated mode, we generate the whole table and then create sub-tables from it. This is not the most efficient way of prover input generation. It works as a workaround, but we need to provide a proper interface and let the user (usually the `proof-producer`) generate only his particular sub-table.

**Suggested solution:** evaluate all the components results, but skip their constraints and assignment tables generation.

Depends on: https://github.com/NilFoundation/zkllvm-blueprint/issues/308

**Comment by akokoshn** [comment]
Implementation: https://github.com/NilFoundation/zkLLVM/pull/451
