### ISSUE TITLE
[Feature request]: Add multiprover tests with private input

### ISSUE THREAD

**Issue by ETatuzova** [NilFoundation/zkLLVM#420]
We need a number of  small examples\tests, that can show us that private input feature is compatible with multi-provers.
A good base for it will be merkle tree poseidon example.
It may be easily changed to another hash
- [x] Merkle tree poseidon example with leaves in private input and merkle root in public input. It should check, is merkle proof correct or not.
- [x] Example that computes checks two merkle trees' merkle roots as previous one but each tree should be placed on its own prover. Checks both roots independently.
- [x] Two sub-trees with common root are computed on two provers. Third prover computes hash (root0, roo1 ) and checks it that it equals single public input number.
- [x] Four sub-trees are computed on four provers. Fifth prover computes merkle tree of four elements with subtrees merkle roots as leafs 
- [x] Three layers of merkle trees to check, will shared column contain all necessary data or not.

- https://github.com/NilFoundation/zkLLVM/issues/449

**Comment by CblPOK-git** [comment]
https://github.com/NilFoundation/zkLLVM/pull/436
