### ISSUE TITLE
[Possible bug]  Not found witness in multiprover examples

### ISSUE THREAD

**Issue by CblPOK-git** [NilFoundation/zkLLVM#449]
merkle_poseidon_3provers_cpp_example
merkle_poseidon_5provers_cpp_example
merkle_poseidon_21prover_3layers_cpp_example

**Comment by akokoshn** [comment]
After remove `next_prover` (https://github.com/NilFoundation/zkLLVM/pull/429) locally proving of these examples passed

**Comment by akokoshn** [comment]
Proving passed on linux CI: https://github.com/NilFoundation/zkLLVM/pull/429

**Comment by akokoshn** [comment]
#429 , merged
