### ISSUE TITLE
[Possible bug] Shifts are potentially broken for uint64_t

### ISSUE THREAD

**Issue by color-typea** [NilFoundation/zkLLVM#472]
**Description:** Shifts seems to be broken for uint64_t (and possibly other types) - it seems to work as long as the `shift` used during proof generation is exactly the same as the one used when transpiling the circuit.

**Circuit:**

```
#include <nil/crypto3/hash/algorithm/hash.hpp>
#include <nil/crypto3/hash/sha2.hpp>
#include <cstdint>

// Note: tested both with and without [[private_input]] on all three arguments - behavior is the same
[[circuit]] void shift(uint64_t value, uint64_t shift, uint64_t expected_shifted) {
    uint64_t shifted = value << shift;
    __builtin_assigner_exit_check(shifted == expected_shifted);
}
```

**Private Input:** `[]`
**Public Input:** `[{"int": 1}, {"int": 2}, {"int": 4}]`

**Steps to reproduce:**
1. Compile, assign and transpile (`gen-evm-verifier`) the circuit.
2. Deploy EVM  verifier to hardhat
3. Run proof-producer
4. Submit generated proof to the verifier.
5. Expected result: verification succeeds; Actual result: verification fails.

Alternatively, use a [zkllvm-playgorund](https://github.com/color-typea/zkllvm-playground/blob/364e287c7a6812e7fe35b61be1a72a83f0fdfad1/test/00-playground.ts) test project:

* Checkout the referenced commit (`multiple-test-support` branch, 364e287c7a6812e7fe35b61be1a72a83f0fdfad1 commit)
* make create-env
* Setup "external environment" (expects zkllvm and proof-generator repos to be siblings to zkllvm-playground + assigner/assigner/transpilier/proof-generator being built from source) 
* npx hardhat test test/00-playground.ts
** If first run fails with "... contract was not found" - just rerun the test (transpiling happens after compilation and deployment - this is a know issue I couldn't resolve yer)

**Additional symptoms:**
1. Running transpiler with `gen-test-proof` mode succeeds, including verification.
2. Proof generated by the transpiler behaves the same - only passes if the same shift was used, and fails otherwise

**Comment by makxenov** [comment]
This example has passed the whole pipeline in #478 , so the verifier should be OK
