### ISSUE TITLE
[Possible bug] unsupported opcode type: freeze

### ISSUE THREAD

**Issue by manylov** [NilFoundation/zkLLVM#499]
**Describe the bug**
When trying to run assigner on some circtuits, i got errors like following:
![image](https://github.com/NilFoundation/zkLLVM/assets/738898/892c8b6e-56e8-4b95-959a-57be0c5fe303)
 
I've made some research and found some variations of circuits codes which fail or ran successfully. Put them into the separate repo.

**To Reproduce**
How to reproduce the behavior:
1. Compile circuits from repo i've made for this issue: https://github.com/manylov/zkllvm-issues
2. Run assigner

**Expected behavior**
No error 

**Toolchain versions**
1. Run in zkllvm with docker 0.1.8

**Comment by nkaskov** [comment]
Fixed with this PR: https://github.com/NilFoundation/zkllvm-assigner/pull/169
