### ISSUE TITLE
[Possible bug] private inputs assigner run fails on new zkllvm-template in branch nkaskov-update-cmake

### ISSUE THREAD

**Issue by manylov** [NilFoundation/zkLLVM#500]
**Describe the bug**
Working with https://github.com/NilFoundation/zkllvm-template/tree/nkaskov-update-cmake
Tried to run https://github.com/Resolfinity/zkllvm-casper-experiments/tree/main/4.poseidon-commitment/test-server cpp and input, make worked ok, but assigner not:
![image](https://github.com/NilFoundation/zkLLVM/assets/738898/a2ec65be-333e-4dc2-ab0e-7da5d76d52c0)

Removed [[ptivate_input]] from arguments, and it works. Seems the issue is in [[private_input]]

**To Reproduce**
How to reproduce the behavior:
1. Compile circuit with private inputs, like noted above
2. Run assigner

**Expected behavior**
No error

**Toolchain versions**
1. https://github.com/NilFoundation/zkllvm-template/tree/nkaskov-update-cmake
2. Commit: 8853254331b741ca1c899a02166b80053d2c1cca

**Comment by nkaskov** [comment]
@CblPOK-git , could you please check if it's still present? @manylov checked on this commit: 8853254331b741ca1c899a02166b80053d2c1cca

After this commit, I've substituted the example code and the input with a very simple arithmetic example. It makes sense to restore the old version.

**Comment by CblPOK-git** [comment]
@manylov we moved private inputs to separate file, create second json, move private inputs there and pass file name with -p flag
