### ISSUE TITLE
[Possible bug] fails when array.end() iterator is passed as a function parameter

### ISSUE THREAD

**Issue by ETatuzova** [NilFoundation/zkLLVM#519]
On this example:
```
#include <nil/crypto3/algebra/curves/pallas.hpp>

using namespace nil::crypto3::algebra::curves;

int f(std::array<int,5>::iterator it_begin, std::array<int,5>::iterator it_end) {
    return *it_begin;
}

[[circuit]] int field_for_example() {
    std::array<int, 5> v = {1, 2, 3, 4, 5};

    return f(v.begin(), v.end());
}
```
assigner fails with `undef_type->isAggregateType()` error.

**Comment by akokoshn** [comment]
Fail happens on processing parameters of `call`:
```
%5 = call noundef i32 @_Z1fPiS_(ptr noundef %3, ptr poison)
```
'v.end()' is special llvm constant `poison` which is `UndefValue` and not `AggregateType`, so we have no it in frame of stack.
**It means now `end` iterator can't be used as parameter of instruction.**

**Comment by akokoshn** [comment]
possible solution - process `poison` value as undefined integer constant:
```
if (undef_type->isIntegerTy() || undef_type->isFieldTy() || llvm::isa<llvm::PoisonValue>(c)) {
```

**Comment by akokoshn** [comment]
Fix: https://github.com/NilFoundation/zkllvm-assigner/pull/179
