### ISSUE TITLE
Command to compile own circuit

### ISSUE THREAD

**Issue by manylov** [NilFoundation/zkllvm#56]
Guys, it's unclear how can I make my own .cpp compilation

`make -C ${ZKLLVM_BUILD:-build} circuit_examples -j$(nproc) 
`

what should I put instead of circuit_examples?

**Comment by nkaskov** [comment]
circuit_examples is a target. You need to change the CMakeLists.txt config and set your own source files there. The process is the same as for regular cmake configuration.
